General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captures.apple.com
tun-server = true
dns-server = 1.1.1.1, 8.8.8.8

[Rule]
# Định tuyến trực tiếp để tránh lag khi upload/download ảnh Locket
DOMAIN-SUFFIX, locket.camera, DIRECT
DOMAIN-SUFFIX, locket-app.com, DIRECT
FINAL, DIRECT

[Script]
# Gọi Script từ Repo GitHub (Đã sửa URL chuẩn đuôi .js)
Locket_Gold = type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),requires-body=true,max-size=-1,timeout=60,script-path=https://raw.githubusercontent.com/nguyenvanloi1212a-wq/Locketloi/refs/heads/main/Prolocket.js

[MITM]
# Chặn bắt gói tin từ hệ thống thanh toán RevenueCat
hostname = api.revenuecat.com
