[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captures.apple.com
tun-server = true
dns-server = 1.1.1.1, 8.8.8.8

[Rule]
# Định tuyến trực tiếp để tránh lag khi upload/download ảnh Locket
DOMAIN-SUFFIX, locket.camera, DIRECT
DOMAIN-SUFFIX, locket-app.com, DIRECT
FINAL, DIRECT

[Script]
# 1. Script xử lý Yêu cầu (HTTP Request) - Xóa Header để tránh lưu cache (Lỗi 304 Not Modified)
Delete_Header = type=http-request,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),script-path=https://raw.githubusercontent.com/nguyenvanloi1212a-wq/locketgoldlllll/refs/heads/main/deleteHeader_Loi.js

# 2. Script xử lý Phản hồi (HTTP Response) - Mở khóa tính năng Premium
Locket_Gold = type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$),requires-body=true,max-size=-1,timeout=60,script-path=https://raw.githubusercontent.com/nguyenvanloi1212a-wq/locketgoldlllll/refs/heads/main/Locket_Loi.js

[MITM]
# Chặn bắt gói tin từ hệ thống thanh toán RevenueCat
hostname = api.revenuecat.com
